### ISSUE TITLE
uninitialized constant #<Class:Obscenity::Base>::YAML with rspec

### ISSUE THREAD

**Issue by embasbm** [tjackiw/obscenity#27]
Hi everyone, I'm having an issue and have no idea where to ask for help:
I want to test (rspec) my MyModel which does use Obscenity:
```
require 'obscenity'
module MyModel
  def check_for_obscene_words
     offensive_words = Obscenity.offensive(review.text)
  end
end
```
I got this:

> uninitialized constant #<Class:Obscenity::Base>::YAML

When I use `byebug` right before or after the call, everything is just fine, and the test runs green.

**Comment by jerodsanto** [comment]
@embasbm see #16. Since this gem is no longer maintained, adding a `require "yaml"` to your file before you `require "obscenity"` will fix it. `byebug` must load `yaml`, which would explain why it works in that case.
